version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: casepro
      POSTGRES_PASSWORD: nyaruka
      POSTGRES_DB: casepro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  web:
    build: .
    command: gunicorn casepro.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://casepro:casepro123@db/casepro_db
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: casepro.settings
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
